# Generated by Django 6.0.5 on 2026-05-18 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING_CUSTOMER', 'Müşteri Onayı Bekliyor'), ('ACTIVE', 'Aktif'), ('PAID', 'Ödendi'), ('REJECTED', 'Reddedildi')], default='PENDING_CUSTOMER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_as_customer', to='api.customerprofile')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_as_seller', to='api.sellerprofile')),
            ],
            options={
                'verbose_name': 'Veresiye',
                'verbose_name_plural': 'Veresiyeler',
                'db_table': 'debts',
                'ordering': ['-created_at'],
            },
        ),
    ]
