# Generated by Django 6.0.5 on 2026-05-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
