# Generated by Django 6.0.5 on 2026-05-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sellerprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='approval_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='DebtItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.debt')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.medicine')),
            ],
            options={
                'verbose_name': 'Veresiye Kalemi',
                'verbose_name_plural': 'Veresiye Kalemleri',
                'db_table': 'debt_items',
            },
        ),
    ]
